defaults:
  actions:
    backport:
      assignees:
        - "{{ author }}"

queue_rules:
  - name: default
    conditions:
      - "#approved-reviews-by>=1"

pull_request_rules:
  - name: automerge to the base branch with label automerge and branch protection passing
    conditions:
      - "#approved-reviews-by>=1"
      - base=main
      - label=A:automerge
    actions:
      queue:
        name: default
        method: squash
        commit_message_template: |
          {{ title }} (#{{ number }})
          {{ body }}
  - name: backport patches to v3.x branch
    conditions:
      - base=main
      - label=A:backport/v3.x
    actions:
      backport:
        branches:
          - v3.x
  - name: backport patches to v4.x branch
    conditions:
      - base=main
      - label=A:backport/v4.x
    actions:
      backport:
        branches:
          - v4.x
  - name: backport patches to v6.x branch
    conditions:
      - base=main
      - label=A:backport/v6.x
    actions:
      backport:
        branches:
          - v6.x
  - name: backport patches to v8.x branch
    conditions:
      - base=main
      - label=A:backport/v8.x
    actions:
      backport:
        branches:
          - v8.x
  - name: backport patches to v10.x branch
    conditions:
      - base=main
      - label=A:backport/v10.x
    actions:
      backport:
        branches:
          - v10.x
  - name: backport patches to v11.x branch
    conditions:
      - base=main
      - label=A:backport/v11.x
    actions:
      backport:
        branches:
          - v11.x
  - name: backport patches to v12.x branch
    conditions:
      - base=main
      - label=A:backport/v12.x
    actions:
      backport:
        branches:
          - v12.x
  - name: backport patches to v13.x branch
    conditions:
      - base=main
      - label=A:backport/v13.x
    actions:
      backport:
        branches:
          - v13.x
  - name: backport patches to v14.x branch
    conditions:
      - base=main
      - label=A:backport/v14.x
    actions:
      backport:
        branches:
          - v14.x
  - name: backport patches to v15.x branch
    conditions:
      - base=main
      - label=A:backport/v15.x
    actions:
      backport:
        branches:
          - v15.x
  - name: backport patches to v16.x branch
    conditions:
      - base=main
      - label=A:backport/v16.x
    actions:
      backport:
        branches:
          - v16.x
