defaults:
  actions:
    backport:
      assignees:
        - "{{ author }}"

queue_rules:
  - name: default
    queue_conditions:
      - "#approved-reviews-by>=2"
      - base=main
      - label=A:automerge
    merge_conditions:
      - "#approved-reviews-by>=1"
    commit_message_template: |
      {{ title }} (#{{ number }})
      {{ body }}
    merge_method: squash

pull_request_rules:
  - name: backport patches to v3.x branch
    conditions:
      - base=main
      - label=A:backport/v3.x
    actions:
      backport:
        branches:
          - v3.x
  - name: backport patches to v4.x branch
    conditions:
      - base=main
      - label=A:backport/v4.x
    actions:
      backport:
        branches:
          - v4.x
  - name: backport patches to v6.x branch
    conditions:
      - base=main
      - label=A:backport/v6.x
    actions:
      backport:
        branches:
          - v6.x
  - name: backport patches to v8.x branch
    conditions:
      - base=main
      - label=A:backport/v8.x
    actions:
      backport:
        branches:
          - v8.x
  - name: backport patches to v10.x branch
    conditions:
      - base=main
      - label=A:backport/v10.x
    actions:
      backport:
        branches:
          - v10.x
  - name: backport patches to v11.x branch
    conditions:
      - base=main
      - label=A:backport/v11.x
    actions:
      backport:
        branches:
          - v11.x
  - name: backport patches to v12.x branch
    conditions:
      - base=main
      - label=A:backport/v12.x
    actions:
      backport:
        branches:
          - v12.x
  - name: backport patches to v13.x branch
    conditions:
      - base=main
      - label=A:backport/v13.x
    actions:
      backport:
        branches:
          - v13.x
  - name: backport patches to v14.x branch
    conditions:
      - base=main
      - label=A:backport/v14.x
    actions:
      backport:
        branches:
          - v14.x
  - name: backport patches to v15.x branch
    conditions:
      - base=main
      - label=A:backport/v15.x
    actions:
      backport:
        branches:
          - v15.x
  - name: backport patches to v16.x branch
    conditions:
      - base=main
      - label=A:backport/v16.x
    actions:
      backport:
        branches:
          - v16.x
  - name: backport patches to v17.x branch
    conditions:
      - base=main
      - label=A:backport/v17.x
    actions:
      backport:
        branches:
          - v17.x
  - name: backport patches to v18.x branch
    conditions:
      - base=main
      - label=A:backport/v18.x
    actions:
      backport:
        branches:
          - v18.x
  - name: backport patches to v19.x branch
    conditions:
      - base=main
      - label=A:backport/v19.x
    actions:
      backport:
        branches:
          - v19.x
  - name: backport patches to v20.x branch
    conditions:
      - base=main
      - label=A:backport/v20.x
    actions:
      backport:
        branches:
          - v20.x
  - name: backport patches to v21.x branch
    conditions:
      - base=main
      - label=A:backport/v21.x
    actions:
      backport:
        branches:
          - v21.x
  - name: backport patches to v22.x branch
    conditions:
      - base=main
      - label=A:backport/v22.x
    actions:
      backport:
        branches:
          - v22.x
  - name: backport patches to v23.x branch
    conditions:
      - base=main
      - label=A:backport/v23.x
    actions:
      backport:
        branches:
          - v23.x
          - v23.x-iavl-v1
  - name: backport patches to v24.x branch
    conditions:
      - base=main
      - label=A:backport/v24.x
    actions:
      backport:
        branches:
          - v24.x
  - name: backport patches to v25.x branch
    conditions:
      - base=main
      - label=A:backport/v25.x
    actions:
      backport:
        branches:
          - v25.x
  - name: backport patches to v26.x branch
    conditions:
      - base=main
      - label=A:backport/v26.x
    actions:
      backport:
        branches:
          - v26.x
  - name: backport patches to v27.x branch
    conditions:
      - base=main
      - label=A:backport/v27.x
    actions:
      backport:
        branches:
          - v27.x
  - name: backport patches to v28.x branch
    conditions:
      - base=main
      - label=A:backport/v28.x
    actions:
      backport:
        branches:
          - v28.x
  - name: backport patches to v29.x branch
    conditions:
      - base=main
      - label=A:backport/v29.x
    actions:
      backport:
        branches:
          - v29.x
  - name: automerge to the base branch with label automerge and branch protection
      passing
    conditions: []
    actions:
      queue:
