package types

const (
	TypeEvtCreatePosition            = "create_position"
	TypeEvtWithdrawPosition          = "withdraw_position"
	TypeEvtAddToPosition             = "add_to_position"
	TypeEvtTotalCollectSpreadRewards = "total_collect_spread_rewards"
	TypeEvtCollectSpreadRewards      = "collect_spread_rewards"
	TypeEvtTotalCollectIncentives    = "total_collect_incentives"
	TypeEvtCollectIncentives         = "collect_incentives"
	TypeEvtCreateIncentive           = "create_incentive"
	TypeEvtFungifyChargedPosition    = "fungify_charged_position"
	TypeEvtMoveRewards               = "move_rewards"
	TypeEvtCrossTick                 = "cross_tick"
	TypeEvtTransferPositions         = "transfer_positions"

	AttributeValueCategory                                         = ModuleName
	AttributeKeyPositionId                                         = "position_id"
	AttributeKeyNewPositionId                                      = "new_position_id"
	AttributeKeyPoolId                                             = "pool_id"
	AttributeAmount0                                               = "amount0"
	AttributeAmount1                                               = "amount1"
	AttributeKeySpreadFactor                                       = "spread_factor"
	AttributeKeyTokensIn                                           = "tokens_in"
	AttributeKeyTokensOut                                          = "tokens_out"
	AttributeKeyForfeitedTokens                                    = "forfeited_tokens"
	AttributeLiquidity                                             = "liquidity"
	AttributeJoinTime                                              = "join_time"
	AttributeLowerTick                                             = "lower_tick"
	AttributeUpperTick                                             = "upper_tick"
	TypeEvtPoolJoined                                              = "pool_joined"
	TypeEvtPoolExited                                              = "pool_exited"
	TypeEvtTokenSwapped                                            = "token_swapped"
	AttributeIncentiveCoin                                         = "incentive_coin"
	AttributeIncentiveEmissionRate                                 = "incentive_emission_rate"
	AttributeIncentiveStartTime                                    = "incentive_start_time"
	AttributeIncentiveMinUptime                                    = "incentive_min_uptime"
	AttributeInputPositionIds                                      = "input_position_ids"
	AttributeOutputPositionId                                      = "output_position_id"
	AttributePoolAccumName                                         = "pool_accum_name"
	AttributeOldPositionAccumName                                  = "old_position_accum_name"
	AttributeNewPositionAccumName                                  = "new_position_accum_name"
	AttributeGlobalGrowth                                          = "global_growth"
	AttributeInsideGrowth                                          = "inside_growth"
	AttributeMovedRewards                                          = "moved_rewards"
	AttributeClaimableIncentives                                   = "claimable_incentives"
	AttributeKeyTickIndex                                          = "tick_idx"
	AttributeKeySpreadRewardGrowthOppositeDirectionOfLastTraversal = "spread_reward_growth"
	AttributeKeyUptimeGrowthOppositeDirectionOfLastTraversal       = "uptime_growth"
	AttributeNewOwner                                              = "new_owner"
)
