// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: osmosis/authenticator/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	// MaximumUnauthenticatedGas defines the maximum amount of gas that can be
	// used to authenticate a transaction in ante handler without having fee payer
	// authenticated.
	MaximumUnauthenticatedGas uint64 `protobuf:"varint,1,opt,name=maximum_unauthenticated_gas,json=maximumUnauthenticatedGas,proto3" json:"maximum_unauthenticated_gas,omitempty" yaml:"maximum_unauthenticated_gas"`
	// AuthenticatorActiveState defines the state of the authenticator.
	// If set to false, the authenticator module will not be used
	// and the classic cosmos sdk authentication will be used instead.
	AuthenticatorActiveState bool `protobuf:"varint,2,opt,name=authenticator_active_state,json=authenticatorActiveState,proto3" json:"authenticator_active_state,omitempty" yaml:"authenticator_active_state"`
	// CircuitBreakerControllers defines list of addresses that are allowed to
	// set authenticator_active_state without going through governance.
	CircuitBreakerControllers []string `protobuf:"bytes,3,rep,name=circuit_breaker_controllers,json=circuitBreakerControllers,proto3" json:"circuit_breaker_controllers,omitempty" yaml:"circuit_breaker_controllers"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_586bfcb71729932d, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetMaximumUnauthenticatedGas() uint64 {
	if m != nil {
		return m.MaximumUnauthenticatedGas
	}
	return 0
}

func (m *Params) GetAuthenticatorActiveState() bool {
	if m != nil {
		return m.AuthenticatorActiveState
	}
	return false
}

func (m *Params) GetCircuitBreakerControllers() []string {
	if m != nil {
		return m.CircuitBreakerControllers
	}
	return nil
}

func init() {
	proto.RegisterType((*Params)(nil), "osmosis.authenticator.Params")
}

func init() {
	proto.RegisterFile("osmosis/authenticator/params.proto", fileDescriptor_586bfcb71729932d)
}

var fileDescriptor_586bfcb71729932d = []byte{
	// 304 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x3f, 0x4b, 0x03, 0x31,
	0x1c, 0x86, 0x9b, 0x56, 0x8a, 0xde, 0x58, 0x14, 0xae, 0x15, 0xd2, 0x1a, 0x50, 0xba, 0xd8, 0x80,
	0x9d, 0x74, 0xf3, 0x1c, 0x5c, 0xa5, 0xc5, 0xc5, 0x25, 0xfc, 0x2e, 0xc6, 0x6b, 0xf0, 0xd2, 0x94,
	0x24, 0x57, 0xda, 0x6f, 0xe1, 0x17, 0x72, 0x77, 0xec, 0xe8, 0x54, 0xa4, 0xf7, 0x0d, 0xfa, 0x09,
	0xe4, 0xfe, 0x88, 0x3d, 0xc1, 0x6e, 0x09, 0xcf, 0xf3, 0x92, 0xbc, 0xbc, 0x1e, 0xd1, 0x56, 0x69,
	0x2b, 0x2d, 0x85, 0xc4, 0x4d, 0xc4, 0xd4, 0x49, 0x0e, 0x4e, 0x1b, 0x3a, 0x03, 0x03, 0xca, 0x0e,
	0x66, 0x46, 0x3b, 0xdd, 0x3a, 0x29, 0x9d, 0x41, 0xc5, 0xe9, 0x1c, 0x47, 0x3a, 0xd2, 0xb9, 0x41,
	0xb3, 0x53, 0x21, 0x93, 0xf7, 0xba, 0xd7, 0x7c, 0xc8, 0xd3, 0xad, 0x17, 0xef, 0x54, 0xc1, 0x42,
	0xaa, 0x44, 0xb1, 0x64, 0xba, 0x93, 0x15, 0xcf, 0x2c, 0x02, 0xeb, 0xa3, 0x1e, 0xea, 0x1f, 0x04,
	0x17, 0xdb, 0x75, 0x97, 0x2c, 0x41, 0xc5, 0x37, 0x64, 0x8f, 0x4c, 0x46, 0xed, 0x92, 0x3e, 0x56,
	0xe1, 0x3d, 0xd8, 0x16, 0xf7, 0x3a, 0x95, 0x9f, 0x31, 0xe0, 0x4e, 0xce, 0x05, 0xb3, 0x0e, 0x9c,
	0xf0, 0xeb, 0x3d, 0xd4, 0x3f, 0x0c, 0xce, 0xb7, 0xeb, 0xee, 0x59, 0xf1, 0xcc, 0xff, 0x2e, 0x19,
	0xf9, 0x15, 0x78, 0x9b, 0xb3, 0x71, 0x86, 0xb2, 0x32, 0x5c, 0x1a, 0x9e, 0x48, 0xc7, 0x42, 0x23,
	0xe0, 0x55, 0x18, 0xc6, 0xf5, 0xd4, 0x19, 0x1d, 0xc7, 0xc2, 0x58, 0xbf, 0xd1, 0x6b, 0xf4, 0x8f,
	0x76, 0xcb, 0xec, 0x91, 0xc9, 0xa8, 0x5d, 0xd2, 0xa0, 0x80, 0x77, 0xbf, 0x2c, 0x18, 0x7f, 0x6c,
	0x30, 0x5a, 0x6d, 0x30, 0xfa, 0xda, 0x60, 0xf4, 0x96, 0xe2, 0xda, 0x2a, 0xc5, 0xb5, 0xcf, 0x14,
	0xd7, 0x9e, 0xae, 0x23, 0xe9, 0x26, 0x49, 0x38, 0xe0, 0x5a, 0xd1, 0x72, 0x91, 0xcb, 0x18, 0x42,
	0xfb, 0x73, 0xa1, 0xf3, 0xab, 0x21, 0x5d, 0xfc, 0x19, 0xd2, 0x2d, 0x67, 0xc2, 0x86, 0xcd, 0x7c,
	0x9b, 0xe1, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x30, 0x05, 0x38, 0xff, 0xee, 0x01, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CircuitBreakerControllers) > 0 {
		for iNdEx := len(m.CircuitBreakerControllers) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.CircuitBreakerControllers[iNdEx])
			copy(dAtA[i:], m.CircuitBreakerControllers[iNdEx])
			i = encodeVarintParams(dAtA, i, uint64(len(m.CircuitBreakerControllers[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.AuthenticatorActiveState {
		i--
		if m.AuthenticatorActiveState {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if m.MaximumUnauthenticatedGas != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaximumUnauthenticatedGas))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MaximumUnauthenticatedGas != 0 {
		n += 1 + sovParams(uint64(m.MaximumUnauthenticatedGas))
	}
	if m.AuthenticatorActiveState {
		n += 2
	}
	if len(m.CircuitBreakerControllers) > 0 {
		for _, s := range m.CircuitBreakerControllers {
			l = len(s)
			n += 1 + l + sovParams(uint64(l))
		}
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaximumUnauthenticatedGas", wireType)
			}
			m.MaximumUnauthenticatedGas = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaximumUnauthenticatedGas |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuthenticatorActiveState", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.AuthenticatorActiveState = bool(v != 0)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CircuitBreakerControllers", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CircuitBreakerControllers = append(m.CircuitBreakerControllers, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
