version: 2

project_name: symphonyd

env:
  - CGO_ENABLED=1

builds:
  - id: symphonyd-linux-amd64
    main: ./cmd/symphonyd
    binary: symphonyd
    hooks:
      pre:
        - wget https://github.com/CosmWasm/wasmvm/releases/download/{{ .Env.COSMWASM_VERSION }}/libwasmvm_muslc.x86_64.a -O /usr/lib/x86_64-linux-gnu/libwasmvm_muslc.x86_64.a
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CC=x86_64-linux-gnu-gcc
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -X github.com/cosmos/cosmos-sdk/version.Name=symphony
      - -X github.com/cosmos/cosmos-sdk/version.AppName=symphonyd
      - -X github.com/cosmos/cosmos-sdk/version.Version={{ .Version }}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }}
      - -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger,muslc,osusergo
      - -w -s
      - -linkmode=external
      - -extldflags '-Wl,-z,muldefs -static -lm'
    tags:
      - netgo
      - ledger
      - muslc
      - osusergo

  - id: symphonyd-linux-arm64
    main: ./cmd/symphonyd
    binary: symphonyd
    hooks:
      pre:
        - wget https://github.com/CosmWasm/wasmvm/releases/download/{{ .Env.COSMWASM_VERSION }}/libwasmvm_muslc.aarch64.a -O /usr/lib/aarch64-linux-gnu/libwasmvm_muslc.aarch64.a
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CC=aarch64-linux-gnu-gcc
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -X github.com/cosmos/cosmos-sdk/version.Name=symphony
      - -X github.com/cosmos/cosmos-sdk/version.AppName=symphonyd
      - -X github.com/cosmos/cosmos-sdk/version.Version={{ .Version }}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }}
      - -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger,muslc,osusergo
      - -w -s
      - -linkmode=external
      - -extldflags '-Wl,-z,muldefs -static -lm'
    tags:
      - netgo
      - ledger
      - muslc
      - osusergo

archives:
  - id: zipped
    builds:
      # - symphonyd-darwin-universal
      - symphonyd-linux-amd64
      - symphonyd-linux-arm64
      # - symphonyd-darwin-amd64
      # - symphonyd-darwin-arm64
    name_template: "{{.ProjectName}}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format: tar.gz
    files:
      - none*
  - id: binaries
    builds:
      # - symphonyd-darwin-universal
      - symphonyd-linux-amd64
      - symphonyd-linux-arm64
      # - symphonyd-darwin-amd64
      # - symphonyd-darwin-arm64
    name_template: "{{.ProjectName}}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format: binary
    files:
      - none*

checksum:
  name_template: "sha256sum.txt"
  algorithm: sha256

# Docs: https://goreleaser.com/customization/changelog/
changelog:
  disable: true

# Docs: https://goreleaser.com/customization/release/
release:
  github:
    owner: symphony-labs
    name: symphony
  replace_existing_draft: true
  header: |
    < DESCRIPTION OF RELEASE >

    ## Changelog

    See the full changelog [here](https://github.com/symphony-labs/symphony/blob/v{{ .Version }}/CHANGELOG.md)

    ## ⚡️ Binaries

    Binaries for Linux (amd64 and arm64) are available below.

    #### 🔨 Build from source

    If you prefer to build from source, you can use the following commands:

    ````bash
    git clone https://github.com/symphony-labs/symphony
    cd symphony && git checkout v{{ .Version }}
    make install
    ````

    ## 🐳 Run with Docker

    As an alternative to installing and running symphonyd on your system, you may run symphonyd in a Docker container.
    The following Docker images are available in our registry:

    | Image Name                                   | Base                                 | Description                       |
    |----------------------------------------------|--------------------------------------|-----------------------------------|
    | `osmolabs/symphony:{{ .Version }}`            | `distroless/static-debian11`         | Default image based on Distroless |
    | `osmolabs/symphony:{{ .Version }}-distroless` | `distroless/static-debian11`         | Distroless image (same as above)  |
    | `osmolabs/symphony:{{ .Version }}-nonroot`    | `distroless/static-debian11:nonroot` | Distroless non-root image         |
    | `osmolabs/symphony:{{ .Version }}-alpine`     | `alpine`                             | Alpine image                      |

    Example run:

    ```bash
    docker run osmolabs/symphony:{{ .Version }} version
    # v{{ .Version }}
    ````

    All the images support `arm64` and `amd64` architectures.

  name_template: "symphony v{{.Version}} 🧪"
  mode: replace
  draft: true
  
  # Docs: https://goreleaser.com/customization/announce/
  # We could automatically announce the release in
  # - discord
  # - slack
  # - twitter
  # - webhooks
  # - telegram
  # - reddit
  #
  # announce:
  # discord:
  #   enabled: true
  #   message_template: 'New {{.Tag}} is out!'