# Default state for all rules
default: true
MD003:
  # Heading style
  style: 'atx'
MD004: false
# Can't disable MD007 :/
MD007: false
MD009: false
MD010:
  code_blocks: false
MD013: false
MD024: false
MD029: false
MD033: false
MD037: false # breaks on latex
