queue_rules:
  - name: default
    conditions:
      - "#approved-reviews-by>=1"

pull_request_rules:
  - name: automerge to the base branch with label automerge and branch protection passing
    conditions:
      - "#approved-reviews-by>=1"
      - base=main
      - label=A:automerge
    actions:
      queue:
        name: default
        method: squash
        commit_message_template: |
           {{ title }} (#{{ number }})
           {{ body }}
  - name: backport patches to v3.x branch
    conditions:
      - base=main
      - label=A:backport/v3.x
    actions:
      backport:
        branches:
          - v3.x
  - name: backport patches to v4.x branch
    conditions:
      - base=main
      - label=A:backport/v4.x
    actions:
      backport:
        branches:
          - v4.x
  - name: backport patches to v5.x branch
    conditions:
      - base=main
      - label=A:backport/v5.x
    actions:
      backport:
        branches:
          - v5.x
  - name: backport patches to v6.x branch
    conditions:
      - base=main
      - label=A:backport/v6.x
    actions:
      backport:
        branches:
          - v6.x
  - name: backport patches to v7.x branch
    conditions:
      - base=main
      - label=A:backport/v7.x
    actions:
      backport:
        branches:
          - v7.x
