@startuml

left to right direction

legend right
|= Color  |= Transfer |
|<#green> | Outbound  |
|<#blue>  | Inbound   |
endlegend

node "Bitcoin" as bitcoin
node "Osmosis" as osmosis
node "Ethereum" as eth

folder "Observer" as observer {
  folder "Bitcoin" as bitcoin_observer {
    component "Client" as bitcoin_chain_client
    component "Observer" as bitcoin_observer_1
  }

  folder "Ethereum" as eth_observer {
      component "Client" as eth_chain_client
      component "Observer" as eth_observer_1
    }

  folder "Osmosis" as osmosis_observer {
    component "Client" as osmosis_chain_client
    component "Observer" as osmosis_observer_1
  }
}

bitcoin -d-> bitcoin_observer_1 #blue : inbound transfer
bitcoin_observer_1 --d-> osmosis_chain_client #blue

osmosis_observer_1 --u-> bitcoin_chain_client #green
bitcoin_chain_client -u-> bitcoin #green : release coins

eth -d-> eth_observer_1 #blue : inbound transfer
eth_observer_1 --d-> osmosis_chain_client #blue

osmosis_observer_1 --u-> eth_chain_client #green
eth_chain_client -u-> eth #green : release coins

osmosis_chain_client -d-> osmosis #blue : **MsgInboundTransfer**
osmosis -u-> osmosis_observer_1 #green : **EventOutboundTransfer**

@enduml