// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: osmosis/valset-pref/v1beta1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgCreateValidatorSetPreference is a list that holds validator-set.
type MsgSetValidatorSetPreference struct {
	// delegator is the user who is trying to create a validator-set.
	Delegator string `protobuf:"bytes,1,opt,name=delegator,proto3" json:"delegator,omitempty" yaml:"delegator"`
	// list of {valAddr, weight} to delegate to
	Preferences []ValidatorPreference `protobuf:"bytes,2,rep,name=preferences,proto3" json:"preferences" yaml:"preferences"`
}

func (m *MsgSetValidatorSetPreference) Reset()         { *m = MsgSetValidatorSetPreference{} }
func (m *MsgSetValidatorSetPreference) String() string { return proto.CompactTextString(m) }
func (*MsgSetValidatorSetPreference) ProtoMessage()    {}
func (*MsgSetValidatorSetPreference) Descriptor() ([]byte, []int) {
	return fileDescriptor_daa95be02b2fc560, []int{0}
}
func (m *MsgSetValidatorSetPreference) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetValidatorSetPreference) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetValidatorSetPreference.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetValidatorSetPreference) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetValidatorSetPreference.Merge(m, src)
}
func (m *MsgSetValidatorSetPreference) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetValidatorSetPreference) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetValidatorSetPreference.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetValidatorSetPreference proto.InternalMessageInfo

func (m *MsgSetValidatorSetPreference) GetDelegator() string {
	if m != nil {
		return m.Delegator
	}
	return ""
}

func (m *MsgSetValidatorSetPreference) GetPreferences() []ValidatorPreference {
	if m != nil {
		return m.Preferences
	}
	return nil
}

type MsgSetValidatorSetPreferenceResponse struct {
}

func (m *MsgSetValidatorSetPreferenceResponse) Reset()         { *m = MsgSetValidatorSetPreferenceResponse{} }
func (m *MsgSetValidatorSetPreferenceResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSetValidatorSetPreferenceResponse) ProtoMessage()    {}
func (*MsgSetValidatorSetPreferenceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_daa95be02b2fc560, []int{1}
}
func (m *MsgSetValidatorSetPreferenceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetValidatorSetPreferenceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetValidatorSetPreferenceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetValidatorSetPreferenceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetValidatorSetPreferenceResponse.Merge(m, src)
}
func (m *MsgSetValidatorSetPreferenceResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetValidatorSetPreferenceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetValidatorSetPreferenceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetValidatorSetPreferenceResponse proto.InternalMessageInfo

// MsgDelegateToValidatorSet allows users to delegate to an existing
// validator-set
type MsgDelegateToValidatorSet struct {
	// delegator is the user who is trying to delegate.
	Delegator string `protobuf:"bytes,1,opt,name=delegator,proto3" json:"delegator,omitempty" yaml:"delegator"`
	// the amount of tokens the user is trying to delegate.
	// For ex: delegate 10osmo with validator-set {ValA -> 0.5, ValB -> 0.3, ValC
	// -> 0.2} our staking logic would attempt to delegate 5osmo to A , 3osmo to
	// B, 2osmo to C.
	Coin types.Coin `protobuf:"bytes,2,opt,name=coin,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coin" json:"coin"`
}

func (m *MsgDelegateToValidatorSet) Reset()         { *m = MsgDelegateToValidatorSet{} }
func (m *MsgDelegateToValidatorSet) String() string { return proto.CompactTextString(m) }
func (*MsgDelegateToValidatorSet) ProtoMessage()    {}
func (*MsgDelegateToValidatorSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_daa95be02b2fc560, []int{2}
}
func (m *MsgDelegateToValidatorSet) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDelegateToValidatorSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDelegateToValidatorSet.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDelegateToValidatorSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDelegateToValidatorSet.Merge(m, src)
}
func (m *MsgDelegateToValidatorSet) XXX_Size() int {
	return m.Size()
}
func (m *MsgDelegateToValidatorSet) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDelegateToValidatorSet.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDelegateToValidatorSet proto.InternalMessageInfo

func (m *MsgDelegateToValidatorSet) GetDelegator() string {
	if m != nil {
		return m.Delegator
	}
	return ""
}

func (m *MsgDelegateToValidatorSet) GetCoin() types.Coin {
	if m != nil {
		return m.Coin
	}
	return types.Coin{}
}

type MsgDelegateToValidatorSetResponse struct {
}

func (m *MsgDelegateToValidatorSetResponse) Reset()         { *m = MsgDelegateToValidatorSetResponse{} }
func (m *MsgDelegateToValidatorSetResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDelegateToValidatorSetResponse) ProtoMessage()    {}
func (*MsgDelegateToValidatorSetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_daa95be02b2fc560, []int{3}
}
func (m *MsgDelegateToValidatorSetResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDelegateToValidatorSetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDelegateToValidatorSetResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDelegateToValidatorSetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDelegateToValidatorSetResponse.Merge(m, src)
}
func (m *MsgDelegateToValidatorSetResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDelegateToValidatorSetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDelegateToValidatorSetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDelegateToValidatorSetResponse proto.InternalMessageInfo

type MsgUndelegateFromValidatorSet struct {
	// delegator is the user who is trying to undelegate.
	Delegator string `protobuf:"bytes,1,opt,name=delegator,proto3" json:"delegator,omitempty" yaml:"delegator"`
	// the amount the user wants to undelegate
	// For ex: Undelegate 10osmo with validator-set {ValA -> 0.5, ValB -> 0.3,
	// ValC
	// -> 0.2} our undelegate logic would attempt to undelegate 5osmo from A ,
	// 3osmo from B, 2osmo from C
	Coin types.Coin `protobuf:"bytes,3,opt,name=coin,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coin" json:"coin"`
}

func (m *MsgUndelegateFromValidatorSet) Reset()         { *m = MsgUndelegateFromValidatorSet{} }
func (m *MsgUndelegateFromValidatorSet) String() string { return proto.CompactTextString(m) }
func (*MsgUndelegateFromValidatorSet) ProtoMessage()    {}
func (*MsgUndelegateFromValidatorSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_daa95be02b2fc560, []int{4}
}
func (m *MsgUndelegateFromValidatorSet) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUndelegateFromValidatorSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUndelegateFromValidatorSet.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUndelegateFromValidatorSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUndelegateFromValidatorSet.Merge(m, src)
}
func (m *MsgUndelegateFromValidatorSet) XXX_Size() int {
	return m.Size()
}
func (m *MsgUndelegateFromValidatorSet) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUndelegateFromValidatorSet.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUndelegateFromValidatorSet proto.InternalMessageInfo

func (m *MsgUndelegateFromValidatorSet) GetDelegator() string {
	if m != nil {
		return m.Delegator
	}
	return ""
}

func (m *MsgUndelegateFromValidatorSet) GetCoin() types.Coin {
	if m != nil {
		return m.Coin
	}
	return types.Coin{}
}

type MsgUndelegateFromValidatorSetResponse struct {
}

func (m *MsgUndelegateFromValidatorSetResponse) Reset()         { *m = MsgUndelegateFromValidatorSetResponse{} }
func (m *MsgUndelegateFromValidatorSetResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUndelegateFromValidatorSetResponse) ProtoMessage()    {}
func (*MsgUndelegateFromValidatorSetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_daa95be02b2fc560, []int{5}
}
func (m *MsgUndelegateFromValidatorSetResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUndelegateFromValidatorSetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUndelegateFromValidatorSetResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUndelegateFromValidatorSetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUndelegateFromValidatorSetResponse.Merge(m, src)
}
func (m *MsgUndelegateFromValidatorSetResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUndelegateFromValidatorSetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUndelegateFromValidatorSetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUndelegateFromValidatorSetResponse proto.InternalMessageInfo

type MsgRedelegateValidatorSet struct {
	// delegator is the user who is trying to create a validator-set.
	Delegator string `protobuf:"bytes,1,opt,name=delegator,proto3" json:"delegator,omitempty" yaml:"delegator"`
	// list of {valAddr, weight} to delegate to
	Preferences []ValidatorPreference `protobuf:"bytes,2,rep,name=preferences,proto3" json:"preferences" yaml:"preferences"`
}

func (m *MsgRedelegateValidatorSet) Reset()         { *m = MsgRedelegateValidatorSet{} }
func (m *MsgRedelegateValidatorSet) String() string { return proto.CompactTextString(m) }
func (*MsgRedelegateValidatorSet) ProtoMessage()    {}
func (*MsgRedelegateValidatorSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_daa95be02b2fc560, []int{6}
}
func (m *MsgRedelegateValidatorSet) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRedelegateValidatorSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRedelegateValidatorSet.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRedelegateValidatorSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRedelegateValidatorSet.Merge(m, src)
}
func (m *MsgRedelegateValidatorSet) XXX_Size() int {
	return m.Size()
}
func (m *MsgRedelegateValidatorSet) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRedelegateValidatorSet.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRedelegateValidatorSet proto.InternalMessageInfo

func (m *MsgRedelegateValidatorSet) GetDelegator() string {
	if m != nil {
		return m.Delegator
	}
	return ""
}

func (m *MsgRedelegateValidatorSet) GetPreferences() []ValidatorPreference {
	if m != nil {
		return m.Preferences
	}
	return nil
}

type MsgRedelegateValidatorSetResponse struct {
}

func (m *MsgRedelegateValidatorSetResponse) Reset()         { *m = MsgRedelegateValidatorSetResponse{} }
func (m *MsgRedelegateValidatorSetResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRedelegateValidatorSetResponse) ProtoMessage()    {}
func (*MsgRedelegateValidatorSetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_daa95be02b2fc560, []int{7}
}
func (m *MsgRedelegateValidatorSetResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRedelegateValidatorSetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRedelegateValidatorSetResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRedelegateValidatorSetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRedelegateValidatorSetResponse.Merge(m, src)
}
func (m *MsgRedelegateValidatorSetResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRedelegateValidatorSetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRedelegateValidatorSetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRedelegateValidatorSetResponse proto.InternalMessageInfo

// MsgWithdrawDelegationRewards allows user to claim staking rewards from the
// validator set.
type MsgWithdrawDelegationRewards struct {
	// delegator is the user who is trying to claim staking rewards.
	Delegator string `protobuf:"bytes,1,opt,name=delegator,proto3" json:"delegator,omitempty" yaml:"delegator"`
}

func (m *MsgWithdrawDelegationRewards) Reset()         { *m = MsgWithdrawDelegationRewards{} }
func (m *MsgWithdrawDelegationRewards) String() string { return proto.CompactTextString(m) }
func (*MsgWithdrawDelegationRewards) ProtoMessage()    {}
func (*MsgWithdrawDelegationRewards) Descriptor() ([]byte, []int) {
	return fileDescriptor_daa95be02b2fc560, []int{8}
}
func (m *MsgWithdrawDelegationRewards) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgWithdrawDelegationRewards) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgWithdrawDelegationRewards.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgWithdrawDelegationRewards) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgWithdrawDelegationRewards.Merge(m, src)
}
func (m *MsgWithdrawDelegationRewards) XXX_Size() int {
	return m.Size()
}
func (m *MsgWithdrawDelegationRewards) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgWithdrawDelegationRewards.DiscardUnknown(m)
}

var xxx_messageInfo_MsgWithdrawDelegationRewards proto.InternalMessageInfo

func (m *MsgWithdrawDelegationRewards) GetDelegator() string {
	if m != nil {
		return m.Delegator
	}
	return ""
}

type MsgWithdrawDelegationRewardsResponse struct {
}

func (m *MsgWithdrawDelegationRewardsResponse) Reset()         { *m = MsgWithdrawDelegationRewardsResponse{} }
func (m *MsgWithdrawDelegationRewardsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgWithdrawDelegationRewardsResponse) ProtoMessage()    {}
func (*MsgWithdrawDelegationRewardsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_daa95be02b2fc560, []int{9}
}
func (m *MsgWithdrawDelegationRewardsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgWithdrawDelegationRewardsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgWithdrawDelegationRewardsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgWithdrawDelegationRewardsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgWithdrawDelegationRewardsResponse.Merge(m, src)
}
func (m *MsgWithdrawDelegationRewardsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgWithdrawDelegationRewardsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgWithdrawDelegationRewardsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgWithdrawDelegationRewardsResponse proto.InternalMessageInfo

// MsgDelegateBondedTokens breaks bonded lockup (by ID) of osmo, of
// length <= 2 weeks and takes all that osmo and delegates according to
// delegator's current validator set preference.
type MsgDelegateBondedTokens struct {
	// delegator is the user who is trying to force unbond osmo and delegate.
	Delegator string `protobuf:"bytes,1,opt,name=delegator,proto3" json:"delegator,omitempty" yaml:"delegator"`
	// lockup id of osmo in the pool
	LockID uint64 `protobuf:"varint,2,opt,name=lockID,proto3" json:"lockID,omitempty"`
}

func (m *MsgDelegateBondedTokens) Reset()         { *m = MsgDelegateBondedTokens{} }
func (m *MsgDelegateBondedTokens) String() string { return proto.CompactTextString(m) }
func (*MsgDelegateBondedTokens) ProtoMessage()    {}
func (*MsgDelegateBondedTokens) Descriptor() ([]byte, []int) {
	return fileDescriptor_daa95be02b2fc560, []int{10}
}
func (m *MsgDelegateBondedTokens) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDelegateBondedTokens) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDelegateBondedTokens.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDelegateBondedTokens) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDelegateBondedTokens.Merge(m, src)
}
func (m *MsgDelegateBondedTokens) XXX_Size() int {
	return m.Size()
}
func (m *MsgDelegateBondedTokens) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDelegateBondedTokens.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDelegateBondedTokens proto.InternalMessageInfo

func (m *MsgDelegateBondedTokens) GetDelegator() string {
	if m != nil {
		return m.Delegator
	}
	return ""
}

func (m *MsgDelegateBondedTokens) GetLockID() uint64 {
	if m != nil {
		return m.LockID
	}
	return 0
}

type MsgDelegateBondedTokensResponse struct {
}

func (m *MsgDelegateBondedTokensResponse) Reset()         { *m = MsgDelegateBondedTokensResponse{} }
func (m *MsgDelegateBondedTokensResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDelegateBondedTokensResponse) ProtoMessage()    {}
func (*MsgDelegateBondedTokensResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_daa95be02b2fc560, []int{11}
}
func (m *MsgDelegateBondedTokensResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDelegateBondedTokensResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDelegateBondedTokensResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDelegateBondedTokensResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDelegateBondedTokensResponse.Merge(m, src)
}
func (m *MsgDelegateBondedTokensResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDelegateBondedTokensResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDelegateBondedTokensResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDelegateBondedTokensResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgSetValidatorSetPreference)(nil), "osmosis.valsetpref.v1beta1.MsgSetValidatorSetPreference")
	proto.RegisterType((*MsgSetValidatorSetPreferenceResponse)(nil), "osmosis.valsetpref.v1beta1.MsgSetValidatorSetPreferenceResponse")
	proto.RegisterType((*MsgDelegateToValidatorSet)(nil), "osmosis.valsetpref.v1beta1.MsgDelegateToValidatorSet")
	proto.RegisterType((*MsgDelegateToValidatorSetResponse)(nil), "osmosis.valsetpref.v1beta1.MsgDelegateToValidatorSetResponse")
	proto.RegisterType((*MsgUndelegateFromValidatorSet)(nil), "osmosis.valsetpref.v1beta1.MsgUndelegateFromValidatorSet")
	proto.RegisterType((*MsgUndelegateFromValidatorSetResponse)(nil), "osmosis.valsetpref.v1beta1.MsgUndelegateFromValidatorSetResponse")
	proto.RegisterType((*MsgRedelegateValidatorSet)(nil), "osmosis.valsetpref.v1beta1.MsgRedelegateValidatorSet")
	proto.RegisterType((*MsgRedelegateValidatorSetResponse)(nil), "osmosis.valsetpref.v1beta1.MsgRedelegateValidatorSetResponse")
	proto.RegisterType((*MsgWithdrawDelegationRewards)(nil), "osmosis.valsetpref.v1beta1.MsgWithdrawDelegationRewards")
	proto.RegisterType((*MsgWithdrawDelegationRewardsResponse)(nil), "osmosis.valsetpref.v1beta1.MsgWithdrawDelegationRewardsResponse")
	proto.RegisterType((*MsgDelegateBondedTokens)(nil), "osmosis.valsetpref.v1beta1.MsgDelegateBondedTokens")
	proto.RegisterType((*MsgDelegateBondedTokensResponse)(nil), "osmosis.valsetpref.v1beta1.MsgDelegateBondedTokensResponse")
}

func init() {
	proto.RegisterFile("osmosis/valset-pref/v1beta1/tx.proto", fileDescriptor_daa95be02b2fc560)
}

var fileDescriptor_daa95be02b2fc560 = []byte{
	// 699 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0x4b, 0x4f, 0xd4, 0x5e,
	0x14, 0x9f, 0x0b, 0x84, 0x7f, 0xb8, 0x6c, 0xfe, 0x36, 0x04, 0xa1, 0xd1, 0x0e, 0x54, 0x5e, 0x92,
	0xd0, 0x1b, 0x86, 0x18, 0x05, 0x63, 0xa2, 0x23, 0x31, 0x71, 0x31, 0x89, 0x16, 0xd4, 0xc4, 0x85,
	0x49, 0x67, 0x7a, 0x28, 0x0d, 0x6d, 0xef, 0xa4, 0xf7, 0xf2, 0x5a, 0xb8, 0x72, 0x63, 0x5c, 0x18,
	0x77, 0x26, 0x7e, 0x04, 0x57, 0x7e, 0x0c, 0x96, 0xec, 0x74, 0x05, 0x86, 0x49, 0x74, 0xe3, 0x8a,
	0x4f, 0x60, 0xfa, 0x98, 0x4b, 0x09, 0x73, 0x5b, 0x53, 0x1f, 0x9b, 0x99, 0xe9, 0x9c, 0xf3, 0x3b,
	0xe7, 0x77, 0x7f, 0xe7, 0xd1, 0x8b, 0xa7, 0x28, 0xf3, 0x29, 0x73, 0x19, 0xd9, 0xb1, 0x3c, 0x06,
	0x7c, 0xa1, 0x1d, 0xc2, 0x06, 0xd9, 0x59, 0x6c, 0x02, 0xb7, 0x16, 0x09, 0xdf, 0x33, 0xda, 0x21,
	0xe5, 0x54, 0x51, 0x53, 0x2f, 0x23, 0xf1, 0x8a, 0x9c, 0x8c, 0xd4, 0x49, 0x1d, 0x71, 0xa8, 0x43,
	0x63, 0x37, 0x12, 0xfd, 0x4a, 0x10, 0xea, 0x25, 0xcb, 0x77, 0x03, 0x4a, 0xe2, 0xcf, 0xf4, 0xaf,
	0xaa, 0x43, 0xa9, 0xe3, 0x01, 0x89, 0x9f, 0x9a, 0xdb, 0x1b, 0x84, 0xbb, 0x3e, 0x30, 0x6e, 0xf9,
	0xed, 0xd4, 0x41, 0x6b, 0xc5, 0x69, 0x48, 0xd3, 0x62, 0x20, 0x38, 0xb4, 0xa8, 0x1b, 0xa4, 0xf6,
	0xd9, 0x3c, 0xae, 0x8c, 0x5b, 0x1c, 0x12, 0x47, 0xfd, 0x07, 0xc2, 0x57, 0x1a, 0xcc, 0x59, 0x03,
	0xfe, 0xd4, 0xf2, 0x5c, 0xdb, 0xe2, 0x34, 0x5c, 0x03, 0xfe, 0x28, 0x84, 0x0d, 0x08, 0x21, 0x68,
	0x81, 0x52, 0xc3, 0x43, 0x36, 0x78, 0xe0, 0x44, 0x96, 0x31, 0x34, 0x81, 0xe6, 0x86, 0xea, 0x23,
	0xa7, 0x47, 0xd5, 0xff, 0xf7, 0x2d, 0xdf, 0x5b, 0xd1, 0x85, 0x49, 0x37, 0xcf, 0xdc, 0x14, 0x1f,
	0x0f, 0xb7, 0x45, 0x04, 0x36, 0xd6, 0x37, 0xd1, 0x3f, 0x37, 0x5c, 0x23, 0x86, 0x5c, 0x19, 0x43,
	0x24, 0x3f, 0xcb, 0x5c, 0x57, 0x0f, 0x8e, 0xaa, 0x95, 0xd3, 0xa3, 0xaa, 0x92, 0xa4, 0xca, 0x44,
	0xd4, 0xcd, 0x6c, 0xfc, 0x95, 0xeb, 0x6f, 0xbe, 0x7f, 0x9a, 0x17, 0xd5, 0xc9, 0x3b, 0x8d, 0x3e,
	0x83, 0xa7, 0xf2, 0xec, 0x26, 0xb0, 0x36, 0x0d, 0x18, 0xe8, 0x9f, 0x11, 0x1e, 0x6f, 0x30, 0x67,
	0x35, 0x39, 0x12, 0xac, 0xd3, 0xac, 0x7f, 0x29, 0x4d, 0x5e, 0xe0, 0x81, 0xa8, 0x3e, 0x63, 0x7d,
	0x13, 0x68, 0x6e, 0xb8, 0x36, 0x6e, 0x24, 0x05, 0x34, 0xa2, 0x02, 0x0a, 0x15, 0xee, 0x53, 0x37,
	0xa8, 0x93, 0xe8, 0xd8, 0x1f, 0x8f, 0xab, 0xb3, 0x8e, 0xcb, 0x37, 0xb7, 0x9b, 0x46, 0x8b, 0xfa,
	0x24, 0xad, 0x76, 0xf2, 0xb5, 0xc0, 0xec, 0x2d, 0xc2, 0xf7, 0xdb, 0xc0, 0x62, 0x80, 0x19, 0xc7,
	0x5d, 0x99, 0x89, 0x44, 0x98, 0xcc, 0x88, 0xd0, 0x9b, 0xbb, 0x7e, 0x0d, 0x4f, 0x4a, 0x8d, 0xe2,
	0xf8, 0xc7, 0x08, 0x5f, 0x6d, 0x30, 0xe7, 0x49, 0x90, 0xf2, 0x87, 0x07, 0x21, 0xf5, 0xff, 0x98,
	0x04, 0xfd, 0x7f, 0x49, 0x82, 0xf9, 0x48, 0x82, 0xe9, 0x8c, 0x04, 0x72, 0xfe, 0xfa, 0x2c, 0x9e,
	0xce, 0x75, 0x10, 0x52, 0x7c, 0x4b, 0x3a, 0xc1, 0x84, 0xae, 0xe7, 0x6f, 0xcb, 0xf0, 0x8f, 0xa7,
	0xe3, 0x42, 0x63, 0xf4, 0x3e, 0x4a, 0xda, 0x18, 0xbd, 0x8d, 0x42, 0x8d, 0x97, 0xf1, 0xb6, 0x78,
	0xe6, 0xf2, 0x4d, 0x3b, 0xb4, 0x76, 0xd3, 0x2e, 0x72, 0x69, 0x60, 0xc2, 0xae, 0x15, 0xda, 0xac,
	0x8c, 0x1e, 0x17, 0xc7, 0x57, 0x1a, 0x3e, 0x1d, 0x5f, 0xa9, 0x5d, 0xd0, 0x04, 0x7c, 0x39, 0xd3,
	0xe4, 0x75, 0x1a, 0xd8, 0x60, 0xaf, 0xd3, 0x2d, 0x08, 0x4a, 0x31, 0x54, 0x46, 0xf1, 0xa0, 0x47,
	0x5b, 0x5b, 0x0f, 0x57, 0xe3, 0xe9, 0x1d, 0x30, 0xd3, 0x27, 0x7d, 0x12, 0x57, 0x25, 0x69, 0xba,
	0x4c, 0x6a, 0xaf, 0xfe, 0xc3, 0xfd, 0x0d, 0xe6, 0x28, 0xef, 0x11, 0x1e, 0x97, 0x2f, 0xd9, 0x5b,
	0x79, 0xd5, 0xcf, 0x5b, 0x58, 0xea, 0xdd, 0xb2, 0xc8, 0x2e, 0x43, 0xe5, 0x2d, 0xc2, 0xa3, 0x92,
	0x3d, 0x77, 0xa3, 0x20, 0x78, 0x6f, 0x98, 0x7a, 0xa7, 0x14, 0x4c, 0x10, 0xfa, 0x80, 0xb0, 0x9a,
	0xb3, 0x79, 0x96, 0x0b, 0xa2, 0xcb, 0xa1, 0xea, 0xbd, 0xd2, 0xd0, 0x73, 0x6a, 0x49, 0x76, 0x41,
	0x91, 0x5a, 0xbd, 0x61, 0x85, 0x6a, 0xe5, 0x4f, 0x64, 0xdc, 0x58, 0xf2, 0x79, 0x2c, 0x6a, 0x2c,
	0x29, 0xb2, 0xb0, 0xb1, 0x0a, 0x87, 0x50, 0x79, 0x8d, 0xf0, 0x48, 0xcf, 0x11, 0x5c, 0xfa, 0xc5,
	0xfe, 0xc8, 0x82, 0xd4, 0xdb, 0x25, 0x40, 0x5d, 0x2a, 0xf5, 0xc7, 0x07, 0x27, 0x1a, 0x3a, 0x3c,
	0xd1, 0xd0, 0xd7, 0x13, 0x0d, 0xbd, 0xeb, 0x68, 0x95, 0xc3, 0x8e, 0x56, 0xf9, 0xd2, 0xd1, 0x2a,
	0xcf, 0x6f, 0x66, 0x5e, 0x31, 0x69, 0x82, 0x05, 0xcf, 0x6a, 0x32, 0x22, 0x2e, 0x50, 0x8b, 0xcb,
	0x64, 0xef, 0xdc, 0x35, 0x2a, 0x7e, 0xef, 0x34, 0x07, 0xe3, 0xfb, 0xd3, 0xd2, 0xcf, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x5a, 0xd2, 0x4c, 0x56, 0x16, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// SetValidatorSetPreference creates a set of validator preference.
	// This message will process both create + update request.
	SetValidatorSetPreference(ctx context.Context, in *MsgSetValidatorSetPreference, opts ...grpc.CallOption) (*MsgSetValidatorSetPreferenceResponse, error)
	// DelegateToValidatorSet gets the owner, coins and delegates to a
	// validator-set.
	DelegateToValidatorSet(ctx context.Context, in *MsgDelegateToValidatorSet, opts ...grpc.CallOption) (*MsgDelegateToValidatorSetResponse, error)
	// UndelegateFromValidatorSet gets the owner and coins and undelegates from
	// validator-set. The unbonding logic will follow the `Undelegate` logic from
	// the sdk.
	UndelegateFromValidatorSet(ctx context.Context, in *MsgUndelegateFromValidatorSet, opts ...grpc.CallOption) (*MsgUndelegateFromValidatorSetResponse, error)
	// RedelegateValidatorSet takes the existing validator set and redelegates to
	// a new set.
	RedelegateValidatorSet(ctx context.Context, in *MsgRedelegateValidatorSet, opts ...grpc.CallOption) (*MsgRedelegateValidatorSetResponse, error)
	// WithdrawDelegationRewards allows users to claim rewards from the
	// validator-set.
	WithdrawDelegationRewards(ctx context.Context, in *MsgWithdrawDelegationRewards, opts ...grpc.CallOption) (*MsgWithdrawDelegationRewardsResponse, error)
	// DelegateBondedTokens allows users to break the lockup bond and delegate
	// osmo tokens to a predefined validator-set.
	DelegateBondedTokens(ctx context.Context, in *MsgDelegateBondedTokens, opts ...grpc.CallOption) (*MsgDelegateBondedTokensResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SetValidatorSetPreference(ctx context.Context, in *MsgSetValidatorSetPreference, opts ...grpc.CallOption) (*MsgSetValidatorSetPreferenceResponse, error) {
	out := new(MsgSetValidatorSetPreferenceResponse)
	err := c.cc.Invoke(ctx, "/osmosis.valsetpref.v1beta1.Msg/SetValidatorSetPreference", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DelegateToValidatorSet(ctx context.Context, in *MsgDelegateToValidatorSet, opts ...grpc.CallOption) (*MsgDelegateToValidatorSetResponse, error) {
	out := new(MsgDelegateToValidatorSetResponse)
	err := c.cc.Invoke(ctx, "/osmosis.valsetpref.v1beta1.Msg/DelegateToValidatorSet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UndelegateFromValidatorSet(ctx context.Context, in *MsgUndelegateFromValidatorSet, opts ...grpc.CallOption) (*MsgUndelegateFromValidatorSetResponse, error) {
	out := new(MsgUndelegateFromValidatorSetResponse)
	err := c.cc.Invoke(ctx, "/osmosis.valsetpref.v1beta1.Msg/UndelegateFromValidatorSet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RedelegateValidatorSet(ctx context.Context, in *MsgRedelegateValidatorSet, opts ...grpc.CallOption) (*MsgRedelegateValidatorSetResponse, error) {
	out := new(MsgRedelegateValidatorSetResponse)
	err := c.cc.Invoke(ctx, "/osmosis.valsetpref.v1beta1.Msg/RedelegateValidatorSet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) WithdrawDelegationRewards(ctx context.Context, in *MsgWithdrawDelegationRewards, opts ...grpc.CallOption) (*MsgWithdrawDelegationRewardsResponse, error) {
	out := new(MsgWithdrawDelegationRewardsResponse)
	err := c.cc.Invoke(ctx, "/osmosis.valsetpref.v1beta1.Msg/WithdrawDelegationRewards", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DelegateBondedTokens(ctx context.Context, in *MsgDelegateBondedTokens, opts ...grpc.CallOption) (*MsgDelegateBondedTokensResponse, error) {
	out := new(MsgDelegateBondedTokensResponse)
	err := c.cc.Invoke(ctx, "/osmosis.valsetpref.v1beta1.Msg/DelegateBondedTokens", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// SetValidatorSetPreference creates a set of validator preference.
	// This message will process both create + update request.
	SetValidatorSetPreference(context.Context, *MsgSetValidatorSetPreference) (*MsgSetValidatorSetPreferenceResponse, error)
	// DelegateToValidatorSet gets the owner, coins and delegates to a
	// validator-set.
	DelegateToValidatorSet(context.Context, *MsgDelegateToValidatorSet) (*MsgDelegateToValidatorSetResponse, error)
	// UndelegateFromValidatorSet gets the owner and coins and undelegates from
	// validator-set. The unbonding logic will follow the `Undelegate` logic from
	// the sdk.
	UndelegateFromValidatorSet(context.Context, *MsgUndelegateFromValidatorSet) (*MsgUndelegateFromValidatorSetResponse, error)
	// RedelegateValidatorSet takes the existing validator set and redelegates to
	// a new set.
	RedelegateValidatorSet(context.Context, *MsgRedelegateValidatorSet) (*MsgRedelegateValidatorSetResponse, error)
	// WithdrawDelegationRewards allows users to claim rewards from the
	// validator-set.
	WithdrawDelegationRewards(context.Context, *MsgWithdrawDelegationRewards) (*MsgWithdrawDelegationRewardsResponse, error)
	// DelegateBondedTokens allows users to break the lockup bond and delegate
	// osmo tokens to a predefined validator-set.
	DelegateBondedTokens(context.Context, *MsgDelegateBondedTokens) (*MsgDelegateBondedTokensResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) SetValidatorSetPreference(ctx context.Context, req *MsgSetValidatorSetPreference) (*MsgSetValidatorSetPreferenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetValidatorSetPreference not implemented")
}
func (*UnimplementedMsgServer) DelegateToValidatorSet(ctx context.Context, req *MsgDelegateToValidatorSet) (*MsgDelegateToValidatorSetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelegateToValidatorSet not implemented")
}
func (*UnimplementedMsgServer) UndelegateFromValidatorSet(ctx context.Context, req *MsgUndelegateFromValidatorSet) (*MsgUndelegateFromValidatorSetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UndelegateFromValidatorSet not implemented")
}
func (*UnimplementedMsgServer) RedelegateValidatorSet(ctx context.Context, req *MsgRedelegateValidatorSet) (*MsgRedelegateValidatorSetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RedelegateValidatorSet not implemented")
}
func (*UnimplementedMsgServer) WithdrawDelegationRewards(ctx context.Context, req *MsgWithdrawDelegationRewards) (*MsgWithdrawDelegationRewardsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WithdrawDelegationRewards not implemented")
}
func (*UnimplementedMsgServer) DelegateBondedTokens(ctx context.Context, req *MsgDelegateBondedTokens) (*MsgDelegateBondedTokensResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelegateBondedTokens not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_SetValidatorSetPreference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSetValidatorSetPreference)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetValidatorSetPreference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/osmosis.valsetpref.v1beta1.Msg/SetValidatorSetPreference",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetValidatorSetPreference(ctx, req.(*MsgSetValidatorSetPreference))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DelegateToValidatorSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDelegateToValidatorSet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DelegateToValidatorSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/osmosis.valsetpref.v1beta1.Msg/DelegateToValidatorSet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DelegateToValidatorSet(ctx, req.(*MsgDelegateToValidatorSet))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UndelegateFromValidatorSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUndelegateFromValidatorSet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UndelegateFromValidatorSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/osmosis.valsetpref.v1beta1.Msg/UndelegateFromValidatorSet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UndelegateFromValidatorSet(ctx, req.(*MsgUndelegateFromValidatorSet))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RedelegateValidatorSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRedelegateValidatorSet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RedelegateValidatorSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/osmosis.valsetpref.v1beta1.Msg/RedelegateValidatorSet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RedelegateValidatorSet(ctx, req.(*MsgRedelegateValidatorSet))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_WithdrawDelegationRewards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgWithdrawDelegationRewards)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).WithdrawDelegationRewards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/osmosis.valsetpref.v1beta1.Msg/WithdrawDelegationRewards",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).WithdrawDelegationRewards(ctx, req.(*MsgWithdrawDelegationRewards))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DelegateBondedTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDelegateBondedTokens)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DelegateBondedTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/osmosis.valsetpref.v1beta1.Msg/DelegateBondedTokens",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DelegateBondedTokens(ctx, req.(*MsgDelegateBondedTokens))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "osmosis.valsetpref.v1beta1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetValidatorSetPreference",
			Handler:    _Msg_SetValidatorSetPreference_Handler,
		},
		{
			MethodName: "DelegateToValidatorSet",
			Handler:    _Msg_DelegateToValidatorSet_Handler,
		},
		{
			MethodName: "UndelegateFromValidatorSet",
			Handler:    _Msg_UndelegateFromValidatorSet_Handler,
		},
		{
			MethodName: "RedelegateValidatorSet",
			Handler:    _Msg_RedelegateValidatorSet_Handler,
		},
		{
			MethodName: "WithdrawDelegationRewards",
			Handler:    _Msg_WithdrawDelegationRewards_Handler,
		},
		{
			MethodName: "DelegateBondedTokens",
			Handler:    _Msg_DelegateBondedTokens_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "osmosis/valset-pref/v1beta1/tx.proto",
}

func (m *MsgSetValidatorSetPreference) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetValidatorSetPreference) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetValidatorSetPreference) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Preferences) > 0 {
		for iNdEx := len(m.Preferences) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Preferences[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Delegator) > 0 {
		i -= len(m.Delegator)
		copy(dAtA[i:], m.Delegator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Delegator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSetValidatorSetPreferenceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetValidatorSetPreferenceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetValidatorSetPreferenceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgDelegateToValidatorSet) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDelegateToValidatorSet) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDelegateToValidatorSet) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Coin.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Delegator) > 0 {
		i -= len(m.Delegator)
		copy(dAtA[i:], m.Delegator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Delegator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDelegateToValidatorSetResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDelegateToValidatorSetResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDelegateToValidatorSetResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUndelegateFromValidatorSet) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUndelegateFromValidatorSet) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUndelegateFromValidatorSet) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Coin.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.Delegator) > 0 {
		i -= len(m.Delegator)
		copy(dAtA[i:], m.Delegator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Delegator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUndelegateFromValidatorSetResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUndelegateFromValidatorSetResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUndelegateFromValidatorSetResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgRedelegateValidatorSet) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRedelegateValidatorSet) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRedelegateValidatorSet) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Preferences) > 0 {
		for iNdEx := len(m.Preferences) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Preferences[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Delegator) > 0 {
		i -= len(m.Delegator)
		copy(dAtA[i:], m.Delegator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Delegator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRedelegateValidatorSetResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRedelegateValidatorSetResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRedelegateValidatorSetResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgWithdrawDelegationRewards) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgWithdrawDelegationRewards) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgWithdrawDelegationRewards) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Delegator) > 0 {
		i -= len(m.Delegator)
		copy(dAtA[i:], m.Delegator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Delegator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgWithdrawDelegationRewardsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgWithdrawDelegationRewardsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgWithdrawDelegationRewardsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgDelegateBondedTokens) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDelegateBondedTokens) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDelegateBondedTokens) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LockID != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.LockID))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Delegator) > 0 {
		i -= len(m.Delegator)
		copy(dAtA[i:], m.Delegator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Delegator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDelegateBondedTokensResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDelegateBondedTokensResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDelegateBondedTokensResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgSetValidatorSetPreference) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Delegator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Preferences) > 0 {
		for _, e := range m.Preferences {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgSetValidatorSetPreferenceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgDelegateToValidatorSet) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Delegator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Coin.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgDelegateToValidatorSetResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUndelegateFromValidatorSet) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Delegator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Coin.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUndelegateFromValidatorSetResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgRedelegateValidatorSet) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Delegator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Preferences) > 0 {
		for _, e := range m.Preferences {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgRedelegateValidatorSetResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgWithdrawDelegationRewards) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Delegator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgWithdrawDelegationRewardsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgDelegateBondedTokens) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Delegator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.LockID != 0 {
		n += 1 + sovTx(uint64(m.LockID))
	}
	return n
}

func (m *MsgDelegateBondedTokensResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgSetValidatorSetPreference) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetValidatorSetPreference: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetValidatorSetPreference: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Delegator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Delegator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Preferences", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Preferences = append(m.Preferences, ValidatorPreference{})
			if err := m.Preferences[len(m.Preferences)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetValidatorSetPreferenceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetValidatorSetPreferenceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetValidatorSetPreferenceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDelegateToValidatorSet) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDelegateToValidatorSet: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDelegateToValidatorSet: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Delegator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Delegator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Coin", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Coin.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDelegateToValidatorSetResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDelegateToValidatorSetResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDelegateToValidatorSetResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUndelegateFromValidatorSet) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUndelegateFromValidatorSet: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUndelegateFromValidatorSet: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Delegator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Delegator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Coin", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Coin.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUndelegateFromValidatorSetResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUndelegateFromValidatorSetResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUndelegateFromValidatorSetResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRedelegateValidatorSet) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRedelegateValidatorSet: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRedelegateValidatorSet: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Delegator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Delegator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Preferences", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Preferences = append(m.Preferences, ValidatorPreference{})
			if err := m.Preferences[len(m.Preferences)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRedelegateValidatorSetResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRedelegateValidatorSetResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRedelegateValidatorSetResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgWithdrawDelegationRewards) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgWithdrawDelegationRewards: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgWithdrawDelegationRewards: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Delegator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Delegator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgWithdrawDelegationRewardsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgWithdrawDelegationRewardsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgWithdrawDelegationRewardsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDelegateBondedTokens) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDelegateBondedTokens: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDelegateBondedTokens: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Delegator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Delegator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LockID", wireType)
			}
			m.LockID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LockID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDelegateBondedTokensResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDelegateBondedTokensResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDelegateBondedTokensResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
