name: Add new PRs to project

on:
  pull_request:
    types:
      - opened
jobs:
  add-to-project:
    name: Add PR to chain dev project
    if: ${{ github.event.pull_request.head.repo.full_name == 'osmosis-labs/osmosis' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/osmosis-labs/projects/1
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
