name: Build and Push E2E Init Chain Images

on:
  push:
    tags:
    - 'v12+.[0-20]+.0+' 
    - 'v[0-20]+.0+.0+' 

env:
  DOCKER_REPOSITORY: osmolabs/osmosis-e2e-init-chain

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v2
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Docker meta (e2e_init_image)
        id: meta_e2e_init_image
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.DOCKER_REPOSITORY }}
          flavor: |
            latest=false
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - 
        name: Build and push (e2e_init_image)
        id: build_push_e2e_init_image
        uses: docker/build-push-action@v2
        with:
          file: tests/e2e/initialization/init.Dockerfile
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            E2E_SCRIPT_NAME=chain
          tags: ${{ steps.meta_e2e_init_image.outputs.tags }}