# This is a manua workflow that does the following when trigerred:
# - Runs a script to find and replace Go import path major version with given version.
# - Commits and pushes changes to the source-branch.
# - Opens a PR from the source branch to the target-branch.

name: Update Go Import Paths

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Current Version that we want to change'
        default: '10'
        required: true
      target-branch:
        description: 'Target Branch'
        default: 'main'
        required: true
      source-branch:
        description: 'Source Branch'
        default: 'update-paths'
        required: true

jobs:
  update-import-paths:
    runs-on: ubuntu-latest

    steps:
      -
        name: Check out repository code
        uses: actions/checkout@v2
      -
        name: Setup Golang
        uses: actions/setup-go@v2.1.4
        with:
          go-version: 1.18
      -
        name: Display go version
        run: go version
      -
        name: Get data from build cache
        uses: actions/cache@v2
        with:
          # In order:
          # * Module download cache
          # * Build cache (Linux)
          # * Build cache (Mac)
          # * Build cache (Windows)
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            ~\AppData\Local\go-build
          key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go-version }}-
      -
        name: Run find & replace script
        run: ./scripts/replace_import_paths.sh ${{ inputs.version }}
      - name: Commit and push changes
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: "auto: update Go import paths to v${{ inputs.version }}"
          target_branch: update-paths
      - name: Open PR
        uses: devops-infra/action-pull-request@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: ${{ github.event.commits[0].message }}
          source_branch: ${{ inputs.source-branch }}
          target_branch: ${{ inputs.target-branch }}
          assignee: ${{ github.actor }}
          draft: true
          label: T:auto,T:code-hygiene
          body: "**Automated pull request**\n\nUpdating Go import paths to v${{ inputs.version }}"
          get_diff: true
