name: Update Comet Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Comet version to use"
        required: true
      branch:
        description: "Branch to update comet version"
        required: true
        default: "main"

jobs:
  update-comet-version-and-create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "^1.22"

      - name: Update Comet Version in Go Mod Files
        run: |
          VERSION="${{ github.event.inputs.version }}"
          echo "Using version: $VERSION"
          MODFILES="./go.mod ./osmoutils/go.mod ./osmomath/go.mod ./x/epochs/go.mod ./x/ibc-hooks/go.mod"
          for modfile in $MODFILES; do
            if [ -e "$modfile" ]; then
              sed -i "s|github.com/osmosis-labs/cometbft v[0-9a-zA-Z.\-]*|github.com/osmosis-labs/cometbft $VERSION|g" $modfile
              cd `dirname $modfile`
              go mod tidy
              cd - > /dev/null
            else
              echo "File $modfile does not exist"
            fi
          done
        shell: bash

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "auto: update osmosis-labs/cometbft to ${{ github.event.inputs.version }}"
          commit-message: "auto: update osmosis-labs/cometbft to ${{ github.event.inputs.version }}"
          body: |
            **Automated pull request**

            Updating osmosis-labs/cometbft dependency to the specified version ${{ github.event.inputs.version }}.
          base: ${{ github.event.inputs.branch }}
          branch-suffix: random
          delete-branch: true
          assignees: ${{ github.actor }}
          labels: "T:auto,A:no-changelog"
